# Generated by Django 3.1.6 on 2021-03-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210323_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default='', upload_to='telusko'),
        ),
    ]
